### ISSUE TITLE
Ｗhen running the code, "core dump!"

### ISSUE THREAD

**Issue by xuduo18311199384** [abner-math/PlaneDetection#9]
It's a great honor to read your paper. But when I am running the code with the comman "./command_line ./plane_datasets/pointclouds/box.pcl ./plane_datasets/pointclouds/result.txt", there is "Detecting planes... core dump" in terminal. May I ask where I have a problem?

**Comment by xuduo18311199384** [comment]
![2021-01-19 15-12-38 的屏幕截图](https://user-images.githubusercontent.com/30895764/105000101-e3ce9f80-5a68-11eb-9488-a6428e6e75b7.png)

**Comment by xuduo18311199384** [comment]
![2021-01-19 15-16-28 的屏幕截图](https://user-images.githubusercontent.com/30895764/105000479-5b9cca00-5a69-11eb-9a4f-e39625a6bd85.png)

**Comment by abner-math** [comment]
@xuduo18311199384 the issue is because the the 'CommandLine' program can only read XYZ point clouds by default (you are trying to pass a .PCL file). If you want to read *.PCL files, modify the line below:

`PointCloud3d *pointCloud = pointCloudIO.loadFromXYZ(inputFileName);`

to

`PointCloud3d *pointCloud = pointCloudIO.loadFromPCL(inputFileName);`

**Comment by xuduo18311199384** [comment]
Thank you very much for your answer.
